algoritmo "aleatorio"

var

x: logico
y: inteiro
z: real
a: caracter
i : inteiro
inicio

aleatorio on

para i de 1 ate 3 faca
     leia(x)
     escreval("VALOR: ",x)
fimpara

para i de 1 ate 3 faca
     leia(y)
     escreval("VALOR: ",y)
fimpara

para i de 1 ate 3 faca
     leia(z)
     escreval("VALOR: ",z)
fimpara

para i de 1 ate 3 faca
     leia(a)
     escreval("VALOR: ",a)
fimpara

fimalgoritmo
