algoritmo "arquivo"

arquivo "../dev.thihup.jvisualg.examples/src/main/resources/dev/thihup/jvisualg/examples/custom/input.txt"

var

x: logico
y: inteiro
z: real
a: caracter
i : inteiro
inicio

para i de 1 ate 3 faca
     leia(x)
     escreval("VALOR LOGICO: ",x)
fimpara

para i de 1 ate 3 faca
     leia(y)
     escreval("VALOR INTEIRO: ",y)
fimpara

para i de 1 ate 3 faca
     leia(z)
     escreval("VALOR REAL: ",z)
fimpara

para i de 1 ate 3 faca
     leia(a)
     escreval("VALOR CARACTER: ",a)
fimpara

fimalgoritmo
